services:

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:1.27.0-alpine
    depends_on:
      - frontend
      - backend
    volumes:
    - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: on-failure

  backend:
    container_name: weatherapp_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: avishniavetski/efi_recruitment:backend-latest
    volumes:
      - backend_volume:/app
      - /app/node_modules
    ports:
      - "${BACKEND_INTERNAL_PORT}"
    restart: on-failure
    environment:
      - PORT=${BACKEND_INTERNAL_PORT}
      - APPID=${BACKEND_APPID}
      - MAP_ENDPOINT=${BACKEND_MAP_ENDPOINT}
      - TARGET_CITY=${BACKEND_TARGET_CITY}
    
  frontend:
    container_name: weatherapp_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: avishniavetski/efi_recruitment:frontend-latest
    volumes:
      - frontend_volume:/app
      - /app/node_modules
    command: npm run start
    ports:
      - "${FRONT_PORT}"
    depends_on:
      - backend
    environment:
      - ENDPOINT=${BACKEND_ENDPOINT}
      - HOST=${FRONT_HOST}
      - PORT=${FRONT_PORT}
    restart: on-failure
volumes:
  backend_volume:
  frontend_volume:


